name = "Immanants"
uuid = "ebcaf6b6-efbf-4b51-b8f1-dae9a5f52dfa"
authors = ["David Amaro Alcalá <dav1494@ciencias.unam.mx>"]
version = "0.1.0"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
